name: Publish NuGet Package
on:
  push:
    branches:
      - main
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.0.x'

      - name: Get version
        uses: gittools/actions-gitversion@v0.9.5

      - name: Restore NuGet packages
        run: dotnet restore

      - name: Build and package
        run: dotnet build -c Release --no-restore /p:Version=$(dotnet gitversion -showvariable NuGetPackageVersion)
        working-directory: ./Cantrip.Linq

      - name: Publish NuGet package
        run: dotnet nuget push **/*.nupkg --source https://api.nuget.org/v3/index.json --api-key {{secrets.NUGET_API_KEY }} --skip-duplicate
